# Generated by Django 4.0.3 on 2023-11-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestroundinfo',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contestroundinfo',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contestroundinfo',
            name='vote_date',
            field=models.DateTimeField(),
        ),
    ]
