# Generated by Django 4.0.3 on 2023-11-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_alter_contestroundinfo_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestroundinfo',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contestroundinfo',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contestroundinfo',
            name='vote_date',
            field=models.DateField(),
        ),
    ]
