# Generated by Django 4.0.3 on 2023-12-08 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0007_comment'),
        ('contest', '0005_alter_contestroundinfo_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeling.modeling')),
                ('round_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contestroundinfo')),
            ],
        ),
    ]
