# Generated by Django 4.0.3 on 2023-12-08 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_previouscontest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previouscontest',
            name='modeling',
        ),
        migrations.RemoveField(
            model_name='previouscontest',
            name='round_info',
        ),
        migrations.AddField(
            model_name='previouscontest',
            name='contest_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contest.contest'),
            preserve_default=False,
        ),
    ]
