# Generated by Django 4.0.3 on 2023-11-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0003_alter_modeling_model_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeling',
            name='thumbnail',
            field=models.FileField(default=1, upload_to='thumbnail/'),
            preserve_default=False,
        ),
    ]
