# Generated by Django 4.0.3 on 2023-11-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0004_modeling_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeling',
            name='model_extension',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
