# Generated by Django 4.0.3 on 2023-11-07 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modeling', '0005_modeling_model_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeling',
            name='voter',
            field=models.ManyToManyField(blank=True, null=True, related_name='voter_model', to=settings.AUTH_USER_MODEL),
        ),
    ]
