# Generated by Django 4.0.3 on 2023-11-15 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modeling', '0006_alter_modeling_voter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_model_comment', to=settings.AUTH_USER_MODEL)),
                ('modeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeling.modeling')),
                ('voter', models.ManyToManyField(related_name='voter_model_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
